import type { Metadata } from "next";
// import { Geist } from "next/font/google";
import "./globals.css";
import { DarkRadialLayout } from "@/components/Applayout";
import { QueryProvider } from "@/providers/QueryProvider";
import { Toaster } from "react-hot-toast";

// const geist = Geist({
//   subsets: ["latin"],
//   display: "swap",
//   preload: true,
// });

export const metadata: Metadata = {
  title: "Gemzy",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="data:," />
      </head>
      <body>
        <QueryProvider>
          <DarkRadialLayout>
            <Toaster position="top-right" />
            {children}
          </DarkRadialLayout>
        </QueryProvider>
      </body>
    </html>
  );
}
